# Generated by Django 2.2.10 on 2020-06-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='text',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question_text',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='text',
            new_name='answer_text',
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpoll',
            name='person_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['-start_date', '-end_date'], name='polls_poll_start_d_244885_idx'),
        ),
    ]
